### ISSUE TITLE
Application is shutting down error

### ISSUE THREAD

**Issue by jasonbiondo** [verdie-g/tinder-auto-matcher#12]
It ran ok for 1 day and now I'm getting: 

info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

Any idea how to fix this?

**Comment by verdie-g** [comment]
Most likely your token was expired.

I was not printing the full exception in case of fatal error. This is fixed in https://github.com/verdie-g/tinder-auto-matcher/commit/5295f07df752dc862459b474682e3d660937af6f.
