### ISSUE TITLE
Think it's finally broken.

### ISSUE THREAD

**Issue by pullup** [verdie-g/tinder-auto-matcher#15]
Tried to run it on a bunch of different systems, but keep getting this error on all of them.
I used this program religiously, thanks for all the girls you've gotten me.
Sincerely, 
-PulluP

Error:
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.results[0].s_number | LineNumber: 0 | BytePositionInLine: 20169.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Converters.JsonConverterInt32.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Tinder.TinderClient.Deserialize[T](String json) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 162
   --- End of inner exception stack trace ---
   at Tinder.TinderClient.Deserialize[T](String json) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 166
   at Tinder.TinderClient.Send[TResponse](HttpRequestMessage msg, CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 155
   at Tinder.TinderClient.GetRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 31
   at Tinder.AutoMatcher.Worker.GetRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 101
   at Tinder.AutoMatcher.Worker.GetTeasedRecommendations(ISet`1 teaserPhotoIds, CancellationToken cancellationToken)+MoveNext() in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 71
   at Tinder.AutoMatcher.Worker.GetTeasedRecommendations(ISet`1 teaserPhotoIds, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Tinder.AutoMatcher.Worker.MatchTeasedRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 51
   at Tinder.AutoMatcher.Worker.MatchTeasedRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 51
   at Tinder.AutoMatcher.Worker.ExecuteAsync(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 30
info: Microsoft.Hosting.Lifetime[0]

**Comment by pullup** [comment]
I love you <3

**Comment by ellizamiller001** [comment]
> Tried to run it on a bunch of different systems, but keep getting this error on all of them. I used this program religiously, thanks for all the girls you've gotten me. Sincerely, -PulluP
> 
> Error:
> 
> ```
>  ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.results[0].s_number | LineNumber: 0 | BytePositionInLine: 20169.
>  ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
>    at System.Text.Json.Utf8JsonReader.GetInt32()
>    at System.Text.Json.Serialization.Converters.JsonConverterInt32.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
>    at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
>    at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
>    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
>    --- End of inner exception stack trace ---
>    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
>    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
>    at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
>    at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
>    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
>    at Tinder.TinderClient.Deserialize[T](String json) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 162
>    --- End of inner exception stack trace ---
>    at Tinder.TinderClient.Deserialize[T](String json) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 166
>    at Tinder.TinderClient.Send[TResponse](HttpRequestMessage msg, CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 155
>    at Tinder.TinderClient.GetRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 31
>    at Tinder.AutoMatcher.Worker.GetRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 101
>    at Tinder.AutoMatcher.Worker.GetTeasedRecommendations(ISet`1 teaserPhotoIds, CancellationToken cancellationToken)+MoveNext() in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 71
>    at Tinder.AutoMatcher.Worker.GetTeasedRecommendations(ISet`1 teaserPhotoIds, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>    at Tinder.AutoMatcher.Worker.MatchTeasedRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 51
>    at Tinder.AutoMatcher.Worker.MatchTeasedRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 51
>    at Tinder.AutoMatcher.Worker.ExecuteAsync(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 30
> info: Microsoft.Hosting.Lifetime[0]
> ```

**Comment by princesssoffia01** [comment]
> Tried to run it on a bunch of different systems, but keep getting this error on all of them. I used this program religiously, thanks for all the girls you've gotten me. Sincerely, -PulluP
> 
> Error:
> 
> ```
>  ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.results[0].s_number | LineNumber: 0 | BytePositionInLine: 20169.
>  ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
>    at System.Text.Json.Utf8JsonReader.GetInt32()
>    at System.Text.Json.Serialization.Converters.JsonConverterInt32.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
>    at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
>    at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
>    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
>    --- End of inner exception stack trace ---
>    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
>    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
>    at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
>    at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
>    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
>    at Tinder.TinderClient.Deserialize[T](String json) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 162
>    --- End of inner exception stack trace ---
>    at Tinder.TinderClient.Deserialize[T](String json) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 166
>    at Tinder.TinderClient.Send[TResponse](HttpRequestMessage msg, CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 155
>    at Tinder.TinderClient.GetRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 31
>    at Tinder.AutoMatcher.Worker.GetRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 101
>    at Tinder.AutoMatcher.Worker.GetTeasedRecommendations(ISet`1 teaserPhotoIds, CancellationToken cancellationToken)+MoveNext() in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 71
>    at Tinder.AutoMatcher.Worker.GetTeasedRecommendations(ISet`1 teaserPhotoIds, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>    at Tinder.AutoMatcher.Worker.MatchTeasedRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 51
>    at Tinder.AutoMatcher.Worker.MatchTeasedRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 51
>    at Tinder.AutoMatcher.Worker.ExecuteAsync(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 30
> info: Microsoft.Hosting.Lifetime[0]
> ```

**Comment by psoffie01** [comment]
> Tried to run it on a bunch of different systems, but keep getting this error on all of them. I used this program religiously, thanks for all the girls you've gotten me. Sincerely, -PulluP
> 
> Error:
> 
> ```
>  ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.data.results[0].s_number | LineNumber: 0 | BytePositionInLine: 20169.
>  ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
>    at System.Text.Json.Utf8JsonReader.GetInt32()
>    at System.Text.Json.Serialization.Converters.JsonConverterInt32.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
>    at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
>    at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
>    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
>    --- End of inner exception stack trace ---
>    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
>    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
>    at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
>    at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
>    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
>    at Tinder.TinderClient.Deserialize[T](String json) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 162
>    --- End of inner exception stack trace ---
>    at Tinder.TinderClient.Deserialize[T](String json) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 166
>    at Tinder.TinderClient.Send[TResponse](HttpRequestMessage msg, CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 155
>    at Tinder.TinderClient.GetRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder\TinderClient.cs:line 31
>    at Tinder.AutoMatcher.Worker.GetRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 101
>    at Tinder.AutoMatcher.Worker.GetTeasedRecommendations(ISet`1 teaserPhotoIds, CancellationToken cancellationToken)+MoveNext() in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 71
>    at Tinder.AutoMatcher.Worker.GetTeasedRecommendations(ISet`1 teaserPhotoIds, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>    at Tinder.AutoMatcher.Worker.MatchTeasedRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 51
>    at Tinder.AutoMatcher.Worker.MatchTeasedRecommendations(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 51
>    at Tinder.AutoMatcher.Worker.ExecuteAsync(CancellationToken cancellationToken) in C:\Users\WDAGUtilityAccount\Desktop\tinder-auto-matcher-master\tinder-auto-matcher-master\Tinder.AutoMatcher\Worker.cs:line 30
> info: Microsoft.Hosting.Lifetime[0]
> ```
