### ISSUE TITLE
Handle rate limit error

### ISSUE THREAD

**Issue by metya** [verdie-g/tinder-auto-matcher#3]
Hi! Very good repo and work.

But in my test only for one day I've got fail with
`{"meta":{"status":429},"error":{"message":"RATE_LIMITED","code":42901}}`

I think that possible to handle. I'm not coding in dotnet so I couldn't send PR. But I think it is easy peasy.

**Comment by verdie-g** [comment]
Could this be related to #2 ? Did you get many matches before getting this error ?

**Comment by metya** [comment]
Not at all. Like maybe 10 or something. Maybe less. I was one-time error. Not noted anymore.
