### ISSUE TITLE
[Suggestion] Any possibility of having a way to set your location?

### ISSUE THREAD

**Issue by pullup** [verdie-g/tinder-auto-matcher#4]
Just a little place in the appsettings file to put a long and lat would be incredibly helpful to me and probably many other who travel a bit.

**Comment by verdie-g** [comment]
There are these two endpoints:
https://github.com/verdie-g/tinder-auto-matcher/blob/9ec5f177dca4455a56367e562a97ba1881a0ad68/Tinder/ITinderClient.cs#L90
https://github.com/verdie-g/tinder-auto-matcher/blob/9ec5f177dca4455a56367e562a97ba1881a0ad68/Tinder/ITinderClient.cs#L97
The second one is supposed to work only if you have a tinder plus account and I'm not sure what the second one does. You can try playing with them.

**Comment by pullup** [comment]
I will do that, thanks <3
